### PR TITLE
Add laravel package discovery and inject http client as a dependency to the transactor

### PR DESCRIPTION
**Pull request by weezqyd**
This PR adds laravel 5.5 package discovery.  i have also added a guzzlehttp wrapper that will be injected to the transactor. This will improve the testability  of the Transactor. Exampe
```php

$client = Mockery::mock('Http\Adapter\AdapterInterface')->shouldReceive('post');
// we can now test our transactor without making api call to MPESA server
$transactor = new Transactor($repository, $client);
```
 - Updated phpunit to > =  5.7
 - Apply CS fixes
 - Dependency injection on transactor

### CODE REVIEW

**Comment by SmoDav** [comment]
Great!

**Comment by SmoDav** [comment]
I have removed some of your changes since they introduce some tight coupling and cause more bugs on transition. The rest looks good

**Comment by weezqyd** [comment]
That is so sad though, but coupling nope.  For now i cant comfortably test the Transactor class because it is tightly coupled to the Guzzle Http client, By injecting the http client to the transactor now it becomes ignorant as long we pass a an instance of `AdapterInterface` this is very helpful when testing. 
I will add more tests and add code coverage this will be very helpful for future contributions.

Another Tip!  phpunit v4 is nologer supported consider updating to v5 | v6
Also Add a Contributing.md file with guidelines to anyone that wishes to contribute to the project.

**Comment by SmoDav** [comment]
I do not plan to put a lot of effort on this package since the M-Pesa API is actually changing, the new version will change 90% of the code herein. I would suggest we keep the package simple for now then the new version will include all the major changes. There is a lot I would want to add here but it will all amount to nothing with the new API.

**Pull request merged**
